# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a746ee0da4f7abb4a59dd8fdbb25e24545915a74f34eb12a3e4896ebe4679ee4b3f0bcd1c40bd4d70d8aecdf4aafa2b535536b79eadcbf50c584bce9d1bab7

test:
  secret_key_base: 4184630035b8b448df77072864effc271715be06ae5bad81c9dc4385773a616f3bf69e70bb99a111265830f1d1533bcbab12a8b7e677554f23f70ddcaeeae03f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
